baseURL = 'https://l2s.pages.dev/'
languageCode = 'en-us'
theme = 'anatole'
pygmentsUseClasses = true

[params]
title = "lmbf"
author = "lmbf"
description = """companies like doing layoffs and I like being ready to jump ship"""
profilePicture = "images/pfp.png"
displayMode = "light"
disableThemeSwitcher = true
doNotLoadAnimations = true
contentratio = 0.8
customCss = ["css/syntax.css"]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"
